

- name: setup frontend
  hosts: all
  become: true
  tasks:
    - name: Nginx install
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: Copy Expense configuration file
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Remove existing content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download and Extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Start Nginx
      ansible.builtin.systemd_service:
        name: nginx
        enabled: true
        state : restarted
