- name: Disable default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Configure Backend.service
  ansible.builtin.copy:
    src: backend.service
    dest:  /etc/systemd/system/backend.service

- name: Add Application User
  ansible.builtin.user:
    name: Expense

- name: App Pre-requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: App_prereq



- name: Download Dependencies
  community.general.npm:
    path: /app/location

- name: Reload system D and start backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: yes

- name: Install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Install Python Library
  ansible.builtin.dnf:
    name: python3-PyMySQL
    state: installed

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: mysql-dev.jyothsnashrey.online

#- name: Load Schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /tmp/dump.sql
