- name: Nginx install
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Expense configuration file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: App Pre-requisite
  ansible.builtin.include_role:
    name: Common
    tasks_from: App_prereq

- name: Start Nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state : restarted
