- name: Remove existing content
  ansible.builtin.file:
    path: "{{ app_location}}"
    state: absent

- name: Create App Directory
  ansible.builtin.file:
    path: "{{ app_location }}"
    state: directory
    owner: "{{app_user}}"
#
#- name: Download and Extract app content
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: "{{ app_location }}"
#    remote_src: true


- name: Download and Extract app content from artifactory
  ansible.builtin.unarchive:
    src: https://{{artifactory_user}}:{{artifactory_password}}artifactory-int.jyothsnashrey.online:8081/artifactory/expense-{{ component }}/{{app_version}}.zip
    dest: "{{ app_location }}"
    remote_src: true