- name : Setup Host Name in Prompt
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Node Exporter Service
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: start Node Exporter Service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Copy Elastic Repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install filebeat
  ansible.builtin.dnf:
    name: filebeat
    state: installed

- name: filebeat config update
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: start filebeat
  ansible.builtin.systemd_service:
    name: filebeat
    state: restarted

- name: configure rsyslog
  ansible.builtin.template:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/{{component}}.conf


- name: restart rsyslog
  ansible.builtin.template:
    name: rsyslog
    state: restarted

